// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/arithmetic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje con la operación a realizar.
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`             // Operando A
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`             // Operando B
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"` // "+", "-", "*", "/"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_proto_arithmetic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arithmetic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_arithmetic_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *OperationRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *OperationRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// Respuesta con el resultado (o un mensaje de error).
type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_proto_arithmetic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arithmetic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_arithmetic_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_arithmetic_proto protoreflect.FileDescriptor

const file_proto_arithmetic_proto_rawDesc = "" +
	"\n" +
	"\x16proto/arithmetic.proto\x12\n" +
	"arithmetic\"J\n" +
	"\x10OperationRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\"A\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Z\n" +
	"\x10OperationService\x12F\n" +
	"\aCompute\x12\x1c.arithmetic.OperationRequest\x1a\x1d.arithmetic.OperationResponse2Z\n" +
	"\x10ProcessorService\x12F\n" +
	"\aProcess\x12\x1c.arithmetic.OperationRequest\x1a\x1d.arithmetic.OperationResponseB0Z.github.com/vimsent/arith-grpc-demo/proto;protob\x06proto3"

var (
	file_proto_arithmetic_proto_rawDescOnce sync.Once
	file_proto_arithmetic_proto_rawDescData []byte
)

func file_proto_arithmetic_proto_rawDescGZIP() []byte {
	file_proto_arithmetic_proto_rawDescOnce.Do(func() {
		file_proto_arithmetic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_arithmetic_proto_rawDesc), len(file_proto_arithmetic_proto_rawDesc)))
	})
	return file_proto_arithmetic_proto_rawDescData
}

var file_proto_arithmetic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_arithmetic_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: arithmetic.OperationRequest
	(*OperationResponse)(nil), // 1: arithmetic.OperationResponse
}
var file_proto_arithmetic_proto_depIdxs = []int32{
	0, // 0: arithmetic.OperationService.Compute:input_type -> arithmetic.OperationRequest
	0, // 1: arithmetic.ProcessorService.Process:input_type -> arithmetic.OperationRequest
	1, // 2: arithmetic.OperationService.Compute:output_type -> arithmetic.OperationResponse
	1, // 3: arithmetic.ProcessorService.Process:output_type -> arithmetic.OperationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_arithmetic_proto_init() }
func file_proto_arithmetic_proto_init() {
	if File_proto_arithmetic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_arithmetic_proto_rawDesc), len(file_proto_arithmetic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_arithmetic_proto_goTypes,
		DependencyIndexes: file_proto_arithmetic_proto_depIdxs,
		MessageInfos:      file_proto_arithmetic_proto_msgTypes,
	}.Build()
	File_proto_arithmetic_proto = out.File
	file_proto_arithmetic_proto_goTypes = nil
	file_proto_arithmetic_proto_depIdxs = nil
}
