################  etapa de compilación  ################
FROM golang:1.22-alpine AS builder

WORKDIR /app
# 1) dependencias
COPY go.mod go.sum ./
RUN go mod download

# 2) código fuente
COPY . .

# 3) compilación estática
RUN CGO_ENABLED=0 go build -o /server ./cmd/server

################  imagen final mínima  ################
FROM alpine:3.20

# Copiamos sólo el binario
COPY --from=builder /server /server

# Puerto que escucha el servidor gRPC
EXPOSE 50051

ENTRYPOINT ["/server"]
