# ---------------- build ----------------
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -o /processor ./cmd/processor

# ---------------- run ----------------
FROM alpine:3.20
COPY --from=builder /processor /processor
EXPOSE 50052
ENTRYPOINT ["/processor"]
